# Generated by Django 3.1.5 on 2021-01-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='News & Blogs', max_length=255),
        ),
    ]
