# Generated by Django 3.1.5 on 2021-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
