# Generated by Django 3.1.5 on 2021-01-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_news_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='new',
        ),
    ]
