# Generated by Django 3.1.5 on 2021-01-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210122_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
