# Generated by Django 3.1.5 on 2021-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
